# Generated by Django 3.2.5 on 2021-07-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_slug_category_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_slug',
            new_name='slug',
        ),
    ]
